models/cohortdata.go, models/concept.go
Jira Ticket: [PXP-9801](https://ctds-planx.atlassian.net/browse/PXP-9801)
- changed concept-stats endpoint to count the number of persons with data for all concepts at once
- simplified CSV endpoint by removing `concept` table from query since none of its exclusive fields are used
- removed deprecated code
=> Performance improvements for concept-stats and for full data (CSV) endpoints

models/concept.go
- concept breakdown endpoint query now ignores NULL values found in breakdown field
=> changed query to ignore NULL values for breakdown field

README.md, controllers/cohortdata.go, models/cohortdata.go, openapis/swagger.yaml, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go, tests/testutils.go
Jira Ticket: [PXP-10102](https://ctds-planx.atlassian.net/browse/PXP-10102)
This is needed to make the code consistent now that structured data is used for the the breakdown endpoint since https://github.com/uc-cdis/cohort-middleware/pull/38
- check-overlap endpoint now expects `filtervalue` to be a concept_id (from `observation.value_as_concept_id`)
=> adjust code to consistently use value_as_concept_id

utils/dsn.go
Test adding query timeout to match rds timeout to see if we get around timeout errors with parallel queries
=> test(query-timeout): testing adding query timeout to match rds timeout

README.md, controllers/cohortdata.go, controllers/concept.go, models/cohortdata.go, models/concept.go, models/customgormtypes.go, openapis/swagger.yaml, server/router.go, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go, tests/utils_tests/parsing_test.go, utils/parsing.go
Jira Ticket: [VADC-28](https://ctds-planx.atlassian.net/browse/VADC-28)
- support for custom dichotomous variables in various endpoints
- change a number of endpoints to support a list of generic variables instead of supporting just concepts. Variables can now be concepts or custom dichotomous definitions (formed by cohort pairs)
- removing support for `prefixed_concept_id` and using plain `concept_id` instead in (most?) endpoints
- improved naming in various places
=> Update endpoints to use variables list

models/helper.go, tests/models_tests/models_test.go, tests/setup_local_db/test_data_atlas.sql, tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: [VADC-172](https://ctds-planx.atlassian.net/browse/VADC-172)
- The previous HARE breakdown stats did not consider the potential overlap that can occur between the two cohorts of a dichotomous covariate. The new query takes the UNION of the two cohorts of a custom dichotomous covariate AND excludes the persons that are in the intersection of both cohorts.
=> Adjust breakdown stats to exclude the intersection of cohorts paired as dichotomous covariates

config/development.yaml, main.go, models/cohortdata.go, tests/models_tests/models_test.go, tests/setup_local_db/test_data_results_and_cdm.sql, tests/utils_tests/utils_test.go, utils/parsing.go
Jira Ticket: [VADC-62](https://ctds-planx.atlassian.net/browse/VADC-62)
- New validation method to find duplicated entries in observation table
- The validation will run for specific concept ids that can now be configured in the config .yaml (example added in this PR)
=> New validation method to find duplicated entries in observation table

tests/utils_tests/utils_test.go, utils/histogram.go
Jira Ticket: [VADC-380](https://ctds-planx.atlassian.net/browse/VADC-380)
- Fixes histogram data endpoint to return correct JSON format for the array of "histogram bin" objects
=> Fix: change histogram endpoint output to return correct JSON

README.md, models/cohortdata.go, models/concept.go, models/helper.go, tests/models_tests/models_test.go, tests/setup_local_db/ddl_results_and_cdm.sql, tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: [VADC-394](https://ctds-planx.atlassian.net/browse/VADC-394)
- Using new `observation_continuous` view instead of using the `observation` table should make queries much faster
- Depends on `observation_continuous` existing in DB
[VADC-394]: https://ctds-planx.atlassian.net/browse/VADC-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: use new observation_continuous view to speed up queries

models/helper.go, tests/models_tests/models_test.go, tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: [VADC-422](https://ctds-planx.atlassian.net/browse/VADC-422)
- use INTERSECT around the UNION of each pair to correctly narrow down the result set with the addition of each extra pair to the query
- also improved one of the tests to avoid this specific issue/bug in the future. The test successfully fails with old code and passes with the new one in this PR
[VADC-422]: https://ctds-planx.atlassian.net/browse/VADC-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: use INTERSECT around the UNION of each pair

tests/models_tests/models_test.go, tests/testutils.go
Jira Ticket: [VADC-421](https://ctds-planx.atlassian.net/browse/VADC-421)
- more unit tests for `QueryFilterByCohortPairsHelper`
[VADC-421]: https://ctds-planx.atlassian.net/browse/VADC-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: extra tests for QueryFilterByCohortPairsHelper

controllers/cohortdata.go, models/cohortdata.go, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go
Jira Ticket: [VADC-488](https://ctds-planx.atlassian.net/browse/VADC-488)
- Fixed CSV endpoint to consider all concepts as numeric/continuous concepts since we don't support values as strings
[VADC-488]: https://ctds-planx.atlassian.net/browse/VADC-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: adjust populateConceptValue to read values based on conceptClassId

models/cohortdata.go, models/cohortdefinition.go, tests/models_tests/models_test.go, tests/testutils.go
Jira Ticket: [VADC-507](https://ctds-planx.atlassian.net/browse/VADC-507)
- improve "get all cohort" method so it warns when a `cohort_definition` record is missing when compared to `cohort` table, instead of crashing
-  improve warning regarding duplicated values in `observation` table (this is an already existing check that currently runs on cohort-middleware startup)
[VADC-507]: https://ctds-planx.atlassian.net/browse/VADC-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix cohort listing and improve existing warning on startup

controllers/concept.go, models/concept.go, tests/controllers_tests/controllers_test.go, utils/parsing.go
Jira Ticket: [VADC-614](https://ctds-planx.atlassian.net/browse/VADC-614)
- adjust `concept.RetrieveAttritionTable` to produce rows in new order, where the order of the rows should follow the order of the concept ids and dichotomous pair variables found in the request
[VADC-614]: https://ctds-planx.atlassian.net/browse/VADC-614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: adjust concept.RetrieveAttritionTable to produce rows in new order

controllers/cohortdefinition.go, models/cohortdefinition.go, server/router.go, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go, tests/setup_local_db/ddl_atlas.sql, tests/setup_local_db/test_data_atlas.sql, utils/parsing.go
Jira Ticket: [VADC-618](https://ctds-planx.atlassian.net/browse/VADC-618)
- add "team project" filtering to /cohortdefinition-stats endpoint. This means that the `/cohortdefinition-stats/by-source-id/:sourceid/` got an extra mandatory parameter and looks like this now: `/cohortdefinition-stats/by-source-id/:sourceid/by-team-project/:teamproject`
- a new SQL VIEW should be added to the Atlas/WebAPI database that contains the `sec_` tables (see view added to `tests/setup_local_db/ddl_atlas.sql` [and comment here](https://github.com/uc-cdis/cohort-middleware/pull/81#pullrequestreview-1763246774))
[VADC-618]: https://ctds-planx.atlassian.net/browse/VADC-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: add "team project" filtering to /cohortdefinition-stats endpoint 

README.md, controllers/cohortdata.go, controllers/cohortdefinition.go, controllers/concept.go, middlewares/teamprojectauthz.go, server/router.go, tests/controllers_tests/controllers_test.go, tests/middlewares_tests/middlewares_test.go, tests/models_tests/models_test.go, utils/parsing.go
Jira Ticket: [VADC-839](https://ctds-planx.atlassian.net/browse/VADC-839)
- Add "team project" validation for cohort-middleware cohortData endpoints. This validation is basically an extra authorization validation that checks if cohort access (for any cohorts in variables) is granted to the user through one of his team projects    
- Fix the endpoint `/cohortdefinition-stats/by-source-id/:sourceid/by-team-project` to support a URL query parameter where the "team project" can also start with `/`
- Removed some endpoints that are NOT used by our current frontend. This will break for any clients that happen to use them. This was preferred over implementing extra "team project" validation for endpoints we're not using anyway.
[VADC-839]: …
=> Feat: integrate Arborist validation for team project for cohort data endpoints AND remove unused endpoints

controllers/cohortdata.go, models/cohortdata.go, models/concept.go, models/helper.go, server/router.go, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go, tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: [VADC-995](https://ctds-planx.atlassian.net/browse/VADC-995)
- Performance improvements for long running queries
- Fixed method name `RetrieveCohortOverlapStatsWithoutFilteringOnConceptValue` .... this name did not reflect what the method is doing... it is a left-over of a [previous change](https://github.com/uc-cdis/cohort-middleware/commit/b13f1d2e4e688eb0077247a7f9dd9e3fb4e8d116).
- Adjusted and improved some tests in model layer
[VADC-995]: https://ctds-planx.atlassian.net/browse/VADC-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: remove unnecessary joins on observation

utils/histogram.go
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1117
- Some concepts have a strange distribution of values and result in crazy number of bins when running through the current histogram binning logic. This PR introduces a naive/simple fallback binning step to avoid these edge cases.
=> idea: add naive binning fallback

models/source.go, tests/setup_local_db/test_data_atlas.sql
Link to JIRA ticket if there is one: [VADC-1135](https://ctds-planx.atlassian.net/browse/VADC-1135)
* WebAPI doesn't support `daimon_type` equal to 6, because of [this](https://github.com/uc-cdis/WebAPI/blob/f23606c97591469b1dc61406226158407dddf5f2/src/main/java/org/ohdsi/webapi/source/SourceDaimon.java#L45)
[VADC-1135]: https://ctds-planx.atlassian.net/browse/VADC-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: do not put data in "source_daimon" table

controllers/version.go, models/source.go, models/version.go, server/router.go, tests/models_tests/models_test.go, tests/setup_local_db/ddl_atlas.sql, tests/setup_local_db/ddl_results_and_cdm.sql, tests/setup_local_db/test_data_atlas.sql, tests/setup_local_db/test_data_results_and_cdm.sql
https://ctds-planx.atlassian.net/browse/VADC-1315
Add a new  endpoint to return the current schema version from Atlas DB OMOP/CDM DB
=> Add new schema_version endpoint

.secrets.baseline, README.md, controllers/cohortdata.go, controllers/concept.go, models/cohortdata.go, models/helper.go, server/router.go, tests/controllers_tests/controllers_test.go, tests/models_tests/models_test.go, tests/testutils.go, tests/utils_tests/utils_test.go, utils/db.go, utils/dsn.go, utils/parsing.go, utils/temptablecache.go
Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/VADC-1584
- new support for filters and transformation arguments in histogram endpoint
- cohort-middleware might need an extra permission to create temp tables
=> Feat: support filters and transformation
