uc-cdis/cohort-middleware

- .github/workflows/image_build_push.yaml
* Use GitHub Action to build Docker image and push to Quay and ECR
> feat: adding GitHub Actions to build Docker image

- controllers/cohort.go
- controllers/cohortdefinition.go
- db/db.go
- models/cohort.go
- models/cohortdata.go
- models/cohortdefinition.go
- models/concept.go
- models/source.go
- tests/test_data_atlas.sql
- utils/db.go
Jira Ticket: [PXP-9797](https://ctds-planx.atlassian.net/browse/PXP-9797)
- the code now uses the `source_daimon` table to discover the **real** schema name of OMOP and RESULTS schemas
- better exception handling: In case of DB query errors we now get HTTP 500 error instead of HTTP 200 with empty response.
- some code cleanup
> Use extra table to discover OMOP and RESULTS schema names

- utils/db.go
Jira Ticket: no ticket
- fixed bug where TablePrefix was set incorrectly for sqlserver dbs...
> fix tableprefix bug in sqlserver part

- controllers/concept.go
- models/concept.go
Jira Ticket: NA
- Performance improvement for large cohorts
> Fix performance issue in cohort-stats

- controllers/cohortdata.go
- models/cohortdata.go
Jira Ticket: NA
- Performance improvement for large cohorts (cohort-data CSV endpoint)
> Fix performance issue in cohort-data

- utils/db.go
Jira Ticket: [PXP-9805](https://ctds-planx.atlassian.net/browse/PXP-9805)
- fixed issue where code would open a new connection for every(?) new query. New code now only opens one connection per DB. The max number of connections expected now is = number_of_sources * 2 + 1
- the *2 is = 1 for OMOP, 1 for RESULTS
- the +1 is for Atlas DB
- removed some code duplication
> adjusted db connection code to only open connection once per db

- .secrets.baseline
- controllers/cohortdata.go
- controllers/cohortdefinition.go
- controllers/concept.go
- controllers/source.go
- controllers/version.go
- middlewares/auth.go
- server/server.go
- utils/dsn.go
> fix: golang linter errors

- .github/workflows/codeql-scan.yaml
* add CodeQL scan GitHub action
> feat: codeql scan GitHub action

- .gitignore
- controllers/cohortdefinition.go
- models/cohortdefinition.go
- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
Jira Ticket: [PXP-9815](https://ctds-planx.atlassian.net/browse/PXP-9815)
- `/cohortdefinition-stats/...` now returns stats ordered by size (descending)
> Sort cohort by size

- README.md
- middlewares/auth.go
- tests/middlewares_tests/middlewares_test.go
Jira Ticket: [PXP-9844](https://ctds-planx.atlassian.net/browse/PXP-9844)
- reorganized `middlewares/auth.go` code and added some tests for it
- updated README with info on deployment to QA
- updated README with info about updating Docker dependencies
> Tests for middlewares/auth

- controllers/cohortdata.go
- controllers/concept.go
- models/cohortdefinition.go
- models/concept.go
- server/router.go
- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
Jira Ticket: [PXP-9881](https://ctds-planx.atlassian.net/browse/PXP-9881)
- better test coverage for controller layer
- improved exception handling in some parts
> Improve controller coverage

- .github/workflows/codeql-scan.yaml
* use `master` branch for GitHub Action, need this https://github.com/uc-cdis/.github/pull/17 to be merged
> feat: use master branch for GH Action

- README.md
- controllers/cohortdefinition.go
- controllers/concept.go
- models/concept.go
- server/router.go
- tests/middlewares_tests/middlewares_test.go
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_results_and_cdm.sql
- tests/setup_local_db/test_data_results_and_cdm.sql
- utils/parsing.go
Jira Ticket: related to [PXP-9870](https://ctds-planx.atlassian.net/browse/PXP-9870)
- new test data based on HARE values
- improved some existing tests, naming and respective comments
> Add HARE to test data

- controllers/concept.go
- models/cohortdefinition.go
- server/router.go
- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
Jira Ticket: [PXP-9950](https://ctds-planx.atlassian.net/browse/PXP-9950)
- add attrition table
> attrition csv endpoint

- README.md
- tests/setup_local_db/test_data_results_and_cdm.sql
- tests/testutils.go
Jira Ticket: [PXP-10037](https://ctds-planx.atlassian.net/browse/PXP-10037)
- changed concept id codes for some of the test concepts. It should not affect any of the code, but this change makes is better aligned with other places where HARE is used.
> changing HARE concept ids

- controllers/concept.go
- better exception handling in concept module
> trying to improve exception handling in concept module

- README.md
- controllers/concept.go
- models/concept.go
- openapis/swagger.yaml
- server/router.go
- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_results_and_cdm.sql
- tests/setup_local_db/test_data_results_and_cdm.sql
- utils/parsing.go
Jira Ticket: [PXP-10057](https://ctds-planx.atlassian.net/browse/PXP-10057)
- new endpoint to retrieve concepts by concept type
- removed domain info from multiple concept endpoints
> new endpoint for concepts by type

- openapis/swagger.yaml
Jira Ticket: [PXP-10057](https://ctds-planx.atlassian.net/browse/PXP-10057)
- added swagger docs for new endpoint (concepts by type)
> swagger docs for new endpoint

- controllers/cohortdata.go
- tests/models_tests/models_test.go
- tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: NA
Follow-up on https://github.com/uc-cdis/cohort-middleware/pull/36
- improved tests
> Ignore null values in breakdown endpoint tests

- models/concept.go
- tests/models_tests/models_test.go
Jira Ticket: [PXP-10102](https://ctds-planx.atlassian.net/browse/PXP-10102)
- breakdown endpoints now return more details (not only concept value but also concept value name)
> adjust Breakdown-Stats to coded values and respective value names

- controllers/cohortdata.go
- tests/controllers_tests/controllers_test.go
Jira Ticket: NA
- change column name from `2_3` to `ID_2_3`
> feat update column name

- controllers/concept.go
- models/cohortdefinition.go
- server/router.go
- tests/controllers_tests/controllers_test.go
Jira Ticket: [VADC-16](https://ctds-planx.atlassian.net/browse/VADC-16)
- change attrition header from concept values to concept names
> feat use concept names instead of concept value in attrition header

- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
Jira Ticket: [VADC-19](https://ctds-planx.atlassian.net/browse/VADC-19)
- Additional tests
> test additional cohortdata definition tests

- tests/models_tests/models_test.go
- tests/setup_local_db/test_data_results_and_cdm.sql
Jira Ticket: [VADC-9](https://ctds-planx.atlassian.net/browse/VADC-9)
- add test with one person multiple hare variables
> test with 1 person multiple hare

- models/cohortdata.go
- models/cohortdefinition.go
- models/concept.go
- models/source.go
- tests/models_tests/models_test.go
- utils/db.go
Jira Ticket: [VADC-494](https://ctds-planx.atlassian.net/browse/VADC-494)
- New timeout added to all queries
[VADC-494]: https://ctds-planx.atlassian.net/browse/VADC-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding a default timeout to all queries

- .github/labeler.yml
- .github/workflows/labeler.yml
- Jenkinsfile
Jira Ticket: [GQE-142](https://ctds-planx.atlassian.net/browse/GQE-142)
[GQE-142]: https://ctds-planx.atlassian.net/browse/GQE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Jenkinsfile and labeler

- .github/labeler.yml
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> add homepagetest label to PR

- config/development.yaml
- models/datadictionary.go
- models/source.go
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_results_and_cdm.sql
- tests/setup_local_db/test_data_atlas.sql
https://ctds-planx.atlassian.net/browse/VADC-1108
Save Data Dictionary result to misc schema
Need to create misc.data_dictionary_result table 
Insert misc schema into source_daimon with source id of 6.
> Change data dictionary result table schema to misc

- controllers/cohortdefinition.go
- tests/controllers_tests/controllers_test.go
Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/VADC-1063
- Fix: allow access to globally shared cohorts without checking Arborist
> Fix: allow access to globally shared cohorts without checking Arborist

- controllers/cohortdata.go
- models/cohortdata.go
- tests/controllers_tests/controllers_test.go
- tests/models_tests/models_test.go
- tests/testutils.go
Ticket: https://ctds-planx.atlassian.net/browse/VADC-847
Grab hare columns from file instead of hardcoded value
Read concept name from concept table when creating cohort data file
> Update cohort data generation to  read concept name from concept table

- models/helper.go
- tests/controllers_tests/controllers_test.go
- tests/data_generator/datagenerator.go
- tests/setup_local_db/test_data_results_and_cdm.sql
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1047
- Fix: change "ordinal" to "nominal" as the supported `concept_class_id` type
> Fix: change "ordinal" to "nominal" as the supported concept_class_id

- models/cohortdefinition.go
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_atlas.sql
- tests/setup_local_db/test_data_atlas.sql
https://ctds-planx.atlassian.net/browse/VADC-1307
Add cohort details expression to endpoint
> Add cohort details expression to endpoint

- Dockerfile
- models/cohortdefinition.go
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_atlas.sql
- tests/setup_local_db/test_data_atlas.sql
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1341
- Feat: improve cohort stats method performance by avoiding count(*) in cohort table altogether...
> Feat: improve cohort stats method performance

- tests/setup_local_db/test_data_results_and_cdm.sql
https://ctds-planx.atlassian.net/browse/VADC-1390
Update database script to include MVP Ordinal variable
> Update database script to include MVP Ordinal variable

- tests/models_tests/invalidSql.sql
- tests/models_tests/models_test.go
- tests/setup_local_db/ddl_results_and_cdm.sql
- tests/setup_local_db/test_data_results_and_cdm.sql
- tests/testutils.go
https://ctds-planx.atlassian.net/browse/VADC-1060
add SQL failure warning
> add SQL failure warning

- .github/workflows/codeql-scan.yaml
Link to JIRA ticket if there is one: [PXP-11415](https://ctds-planx.atlassian.net/browse/PXP-11415)
* removing deprecated CodeQL Action
[PXP-11415]: https://ctds-planx.atlassian.net/browse/PXP-11415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: rm codeql action
